<%
# Helper method to output the box_urls for Opscode's base boxes
#
# @example
#   opscode_box('ubuntu-10.04') #=> "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box"
#
# @param [String] type
#   the type of box
#
# @return [String]
#   the box URL
def opscode_box(type)
  "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_#{type}_provisionerless.box"
end
%>


driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-10.04
    driver_config:
      box: opscode-ubuntu-10.04
      box_url: <%= opscode_box('ubuntu-10.04') %>
    run_list:
      - recipe[apt]

  - name: ubuntu-12.10
    driver_config:
      box: opscode-ubuntu-12.10
      box_url: <%= opscode_box('ubuntu-12.10') %>
    run_list:
      - recipe[apt]

  - name: ubuntu-13.04
    driver_config:
      box: opscode-ubuntu-13.04
      box_url: <%= opscode_box('ubuntu-13.04') %>
    run_list:
      - recipe[apt]

  - name: centos-6.4
    driver_config:
      box: opscode-centos-6.4
      box_url: <%= opscode_box('centos-6.4') %>

  - name: centos-5.9
    driver_config:
      box: opscode-centos-5.9
      box_url: <%= opscode_box('centos-5.9') %>

suites:
  - name: default
    run_list:
      - recipe[wordpress]
    attributes:
      mysql:
        server_root_password: "Please-Dont-Use-In-Production"
        server_debian_password: "Please-Dont-Use-In-Production"
        server_repl_password: "Please-Dont-Use-In-Production"
